import Testing
@testable import SwiftTerm

// Regression test for the sidebar-resize prompt-duplication bug.
//
// When the user drags the host app's sidebar fast enough that multiple
// SIGWINCHes queue up, the host shell's first redraw uses the OLD
// column count while the buffer is already at the NEW (smaller) column
// count. The right-anchored part of the prompt overflows past the right
// margin and autowraps onto row 1; the cursor ends at column 0 of row 1.
// The shell's NEXT redraw — now at the correct column count — issues
// `\r\r\e[J` and writes a fresh prompt, but `\e[J` only clears below the
// cursor, so the stale prompt above stays visible. Result: prompts stack
// on top of each other.
//
// The fix lives in `cmdEraseInDisplay`: when the cursor is at column 0
// of an autowrapped row, the wrap originated above; walk back through
// the chain so the erase covers the whole stale block, and reposition
// the cursor at the chain's origin.

@Suite("Sidebar-resize prompt duplication")
struct SidebarResizeDuplicationTests {
    /// Reproduce the exact shape of the live trace's #98 event:
    ///   - cols=116, cursor at (49, 0) (post-narrow, pre-feed).
    ///   - First redraw was generated by the shell when it still thought
    ///     it was at cols=121, so it uses `\e[K\e[67C` to right-anchor
    ///     a 4-cell tail. With cols=116, that tail wraps onto row 1 and
    ///     the trailing `\e[71D` clamps the cursor at (0, 1).
    ///   - Second redraw is correctly sized for cols=116. Without the
    ///     fix, its `\r\r\e[J` clears row 1+ but not row 0, and writes
    ///     the new prompt on row 1 — duplicating the prompt visibly.
    @Test
    func staleSizedPromptIsClearedByNextRedraw() {
        let (terminal, _) = TerminalTestHarness.makeTerminal(cols: 116, rows: 53, scrollback: 500)

        // Pre-populate row 0 with 49 cells of leftover content + cursor at
        // (49, 0). This matches the "row 0 trimLen=49, cursor (49,0)" buffer
        // state observed live just before the racing redraws arrive.
        terminal.feed(text: String(repeating: "a", count: 49))
        #expect(terminal.buffer.x == 49 && terminal.buffer.y == 0)

        // Stale prompt: built for cols=121, fed at cols=116. 49 main cells,
        // then `\e[K\e[67C` jumps the cursor to col 116 (clamps to col 115),
        // then 4 right-prompt cells overflow and autowrap to row 1, then
        // `\e[71D` clamps backward at the left margin -> cursor (0, 1).
        let stale = "\r\r\u{1b}[J" + String(repeating: "L", count: 49) +
                    "\u{1b}[K\u{1b}[67C" + "RRRR" + "\u{1b}[71D"
        terminal.feed(text: stale)
        // Sanity-check the stale-redraw outcome (this is the bug-trigger
        // state, regardless of whether the eventual fix runs).
        #expect(terminal.buffer.y == 1, "stale prompt should overflow to row 1")
        #expect(terminal.buffer.lines[terminal.buffer.yBase + 1].isWrapped,
                "row 1 should be marked wrapped from the autowrap")

        // Fresh prompt: correctly sized for cols=116. CUF(62) lands at col
        // 111 (no clamp), 4 right-prompt cells fill 111..114, CUB(66)
        // lands at col 49. With the fix, `\r\r\e[J` at (0, 1) walks the
        // wrap chain up, clears row 0+row 1, and moves the cursor to
        // (0, 0). The fresh prompt then writes on row 0.
        let fresh = "\r\r\u{1b}[J" + String(repeating: "L", count: 49) +
                    "\u{1b}[K\u{1b}[62C" + "RRRR" + "\u{1b}[66D"
        terminal.feed(text: fresh)

        let row0 = terminal.buffer.lines[terminal.buffer.yBase].getTrimmedLength()
        let row1 = terminal.buffer.lines[terminal.buffer.yBase + 1].getTrimmedLength()
        #expect(terminal.buffer.y == 0,
                "expected cursor on row 0 after fresh redraw; got y=\(terminal.buffer.y)")
        #expect(row1 == 0,
                "expected row 1 empty (no duplication); got trimLen=\(row1)")
        #expect(row0 > 0,
                "expected row 0 to hold the fresh prompt; got trimLen=\(row0)")
    }

    /// Sanity: a normal `\e[J` at column 0 of an unwrapped row keeps its
    /// usual semantics (erase-below-cursor, cursor stays put). The fix
    /// must only kick in when the current row is part of a wrapped chain.
    @Test
    func plainEraseDisplayUnchanged() {
        let (terminal, _) = TerminalTestHarness.makeTerminal(cols: 80, rows: 24)
        terminal.feed(text: "hello\r\nworld\r\n")
        // Cursor is now at (0, 2). Row 2 is NOT wrapped (caused by LF).
        #expect(terminal.buffer.y == 2 && terminal.buffer.x == 0)
        terminal.feed(text: "\u{1b}[J")
        // Cursor should not have moved up — row 2 is unwrapped.
        #expect(terminal.buffer.y == 2 && terminal.buffer.x == 0)
        // Rows 0 and 1 should still hold their content.
        let r0 = terminal.buffer.lines[terminal.buffer.yBase].translateToString(
            trimRight: true, startCol: 0, endCol: -1, skipNullCellsFollowingWide: true)
        let r1 = terminal.buffer.lines[terminal.buffer.yBase + 1].translateToString(
            trimRight: true, startCol: 0, endCol: -1, skipNullCellsFollowingWide: true)
        #expect(r0 == "hello")
        #expect(r1 == "world")
    }
}
